// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workout.Api.Data;

#nullable disable

namespace Workout.Api.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260916071008_ImportSourceFiles")]
    partial class ImportSourceFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workout.Api.Data.AiImport", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Calls")
                        .HasColumnType("integer");

                    b.Property<bool>("CatalogStale")
                        .HasColumnType("boolean");

                    b.Property<int>("ChunksDone")
                        .HasColumnType("integer");

                    b.Property<int>("ChunksTotal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutlineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SourceFileExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFileKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnresolvedCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "DocumentHash", "PromptVersion");

                    b.ToTable("Imports", null, t =>
                        {
                            t.HasCheckConstraint("CK_Imports_Stage", "\"Stage\" IN ('outline','extract','done')");

                            t.HasCheckConstraint("CK_Imports_Status", "\"Status\" IN ('pending','ready','failed','accepted','discarded')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.AiUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Date");

                    b.ToTable("Usage");
                });

            modelBuilder.Entity("Workout.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RestAlerts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("dark");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("kg");

                    b.HasKey("Id");

                    b.HasIndex("IdentitySubject")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_RestSeconds", "\"RestSeconds\" >= 0 AND \"RestSeconds\" <= 600");

                            t.HasCheckConstraint("CK_Users_Theme", "\"Theme\" IN ('dark','light')");

                            t.HasCheckConstraint("CK_Users_Unit", "\"Unit\" IN ('kg','lb')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.AuthSession", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Hash");

                    b.HasIndex("Expires");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Workout.Api.Data.CompletedSet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<string>("ResistanceMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<double?>("Rpe")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SessionExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SystemLoadKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("Warmup")
                        .HasColumnType("boolean");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("WorkingSetOrdinal")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "SessionExerciseId", "Position");

                    b.ToTable("Sets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sets_Done", "NOT \"Done\" OR \"Reps\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Sets_Reps", "\"Reps\" IS NULL OR (\"Reps\" > 0 AND \"Reps\" <= 1000)");

                            t.HasCheckConstraint("CK_Sets_ResistanceMode", "\"ResistanceMode\" IN ('external','bodyweight','added','assistance','reps_only')");

                            t.HasCheckConstraint("CK_Sets_Rpe", "\"Rpe\" IS NULL OR (\"Rpe\" >= 1 AND \"Rpe\" <= 10 AND \"Rpe\" * 2 = FLOOR(\"Rpe\" * 2))");

                            t.HasCheckConstraint("CK_Sets_SystemLoad", "\"SystemLoadKg\" IS NULL OR (\"SystemLoadKg\" >= 0 AND \"SystemLoadKg\" <= 1000)");

                            t.HasCheckConstraint("CK_Sets_Weight", "\"WeightKg\" IS NULL OR (\"WeightKg\" >= 0 AND \"WeightKg\" <= 1000)");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Cue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoadModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<double>("LoadStepKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5);

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exercises_LoadModel", "\"LoadModel\" IN ('external','full_bodyweight','bodyweight_context_only','reps_only')");

                            t.HasCheckConstraint("CK_Exercises_LoadStep", "\"LoadStepKg\" >= 0 AND \"LoadStepKg\" <= 50");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Normalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("Normalized")
                        .IsUnique();

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<double>("LastE1rmKg")
                        .HasColumnType("double precision");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("Stalls")
                        .HasColumnType("integer");

                    b.Property<double>("TrendE1rmKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ExerciseId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Progress_ExercisePerUser");

                    b.ToTable("Progress", null, t =>
                        {
                            t.HasCheckConstraint("CK_Progress_E1rm", "\"TrendE1rmKg\" >= 0 AND \"LastE1rmKg\" >= 0");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.IntegrationGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Peer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Peer")
                        .IsUnique();

                    b.ToTable("IntegrationGrants");
                });

            modelBuilder.Entity("Workout.Api.Data.MutationReceipt", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Created");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("Workout.Api.Data.NutritionContextCache", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NutritionContexts");
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramPhase", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePageFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePageTo")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("WeekFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WeekTo")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "Position")
                        .IsUnique();

                    b.HasIndex("UserId", "ProgramId", "WeekFrom", "WeekTo");

                    b.ToTable("ProgramPhases");
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramSkip", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "TemplateId")
                        .IsUnique();

                    b.ToTable("ProgramSkips");
                });

            modelBuilder.Entity("Workout.Api.Data.SessionExercise", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoadModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("PrescriptionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgressionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SequenceGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubstitutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "SessionId", "Position");

                    b.ToTable("SessionExercises");
                });

            modelBuilder.Entity("Workout.Api.Data.TemplateExercise", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SequenceGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubstitutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "TemplateId", "Position");

                    b.ToTable("TemplateExercises");
                });

            modelBuilder.Entity("Workout.Api.Data.TrainingProgram", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("standby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ScheduleAnchor")
                        .HasColumnType("date");

                    b.Property<Guid?>("SourceImportId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC");

                    b.Property<int>("Weeks")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Programs_ActivePerUser")
                        .HasFilter("\"Active\"");

                    b.ToTable("Programs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Programs_Lifecycle", "\"LifecycleStatus\" IN ('standby','active','completed')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutSession", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BodyWeightSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NutritionContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("NutritionContextRevision")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Workouts_ActivePerUser")
                        .HasFilter("\"Active\"");

                    b.HasIndex("UserId", "FinishedAt");

                    b.HasIndex("UserId", "PlannedDate");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhaseWeek")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int?>("Weekday")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "Week", "Position");

                    b.HasIndex("UserId", "ProgramId", "Week", "Weekday");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Workout.Api.Data.AiImport", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.AiUsage", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.AuthSession", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.CompletedSet", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseAlias", b =>
                {
                    b.HasOne("Workout.Api.Data.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseProgress", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.IntegrationGrant", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.MutationReceipt", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.NutritionContextCache", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramPhase", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramSkip", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.SessionExercise", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.TemplateExercise", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.TrainingProgram", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutSession", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutTemplate", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
