// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workout.Api.Data;

#nullable disable

namespace Workout.Api.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20261005024118_SessionStartPlanSnapshot")]
    partial class SessionStartPlanSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workout.Api.Data.AiConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AiConversations");
                });

            modelBuilder.Entity("Workout.Api.Data.AiConversationTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActionsDismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActionsResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssistantReply")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientTurnId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("CloseChat")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConversationVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacetsJson")
                        .HasColumnType("text");

                    b.Property<string>("Intent")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("KeywordsJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ToolTraceJson")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "ClientTurnId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("AiConversationTurns");
                });

            modelBuilder.Entity("Workout.Api.Data.AiImport", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Calls")
                        .HasColumnType("integer");

                    b.Property<bool>("CatalogStale")
                        .HasColumnType("boolean");

                    b.Property<string>("ChunkResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChunksDone")
                        .HasColumnType("integer");

                    b.Property<int>("ChunksTotal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DraftBaselineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoticesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutlineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("PageCoverageJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pages")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SelectedAlternativeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SourceExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceTextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnresolvedCount")
                        .HasColumnType("integer");

                    b.Property<string>("WorkStateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Created");

                    b.HasIndex("SourceExpiresAt");

                    b.HasIndex("UserId", "DocumentHash", "PromptVersion");

                    b.ToTable("Imports", null, t =>
                        {
                            t.HasCheckConstraint("CK_Imports_Stage", "\"Stage\" IN ('outline','select','extract','verify','recover','done','failed')");

                            t.HasCheckConstraint("CK_Imports_Status", "\"Status\" IN ('pending','ready','failed','accepted','discarded')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.AiUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("ChatCachedTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("ChatCalls")
                        .HasColumnType("integer");

                    b.Property<long>("ChatInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("ChatReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Date");

                    b.HasIndex("Date");

                    b.ToTable("Usage");
                });

            modelBuilder.Entity("Workout.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RestAlerts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("dark");

                    b.Property<bool>("TrackRir")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("kg");

                    b.HasKey("Id");

                    b.HasIndex("IdentitySubject")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_RestSeconds", "\"RestSeconds\" >= 0 AND \"RestSeconds\" <= 600");

                            t.HasCheckConstraint("CK_Users_Theme", "\"Theme\" IN ('dark','light')");

                            t.HasCheckConstraint("CK_Users_Unit", "\"Unit\" IN ('kg','lb')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.AuthSession", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Hash");

                    b.HasIndex("Expires");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Workout.Api.Data.CompletedSet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<string>("ResistanceMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Rir")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<double?>("Rpe")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SessionExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SystemLoadKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("Warmup")
                        .HasColumnType("boolean");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("WorkingSetOrdinal")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "SessionExerciseId", "Position");

                    b.ToTable("Sets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sets_Done", "NOT \"Done\" OR \"Reps\" IS NOT NULL OR \"DurationSeconds\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Sets_Duration", "\"DurationSeconds\" IS NULL OR (\"DurationSeconds\" > 0 AND \"DurationSeconds\" <= 7200)");

                            t.HasCheckConstraint("CK_Sets_Reps", "\"Reps\" IS NULL OR (\"Reps\" > 0 AND \"Reps\" <= 1000)");

                            t.HasCheckConstraint("CK_Sets_ResistanceMode", "\"ResistanceMode\" IN ('external','bodyweight','added','assistance','reps_only')");

                            t.HasCheckConstraint("CK_Sets_Rpe", "\"Rpe\" IS NULL OR (\"Rpe\" >= 1 AND \"Rpe\" <= 10 AND \"Rpe\" * 2 = FLOOR(\"Rpe\" * 2))");

                            t.HasCheckConstraint("CK_Sets_SystemLoad", "\"SystemLoadKg\" IS NULL OR (\"SystemLoadKg\" >= 0 AND \"SystemLoadKg\" <= 1000)");

                            t.HasCheckConstraint("CK_Sets_Weight", "\"WeightKg\" IS NULL OR (\"WeightKg\" >= 0 AND \"WeightKg\" <= 1000)");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.CustomExercise", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Free Weights");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoadModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<double>("LoadStepKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5);

                    b.Property<string>("LoadStepUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("kg");

                    b.Property<string>("MovementPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryMusclesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("reps");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("CustomExercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomExercises_Category", "\"Category\" IN ('Free Weights','Machine','Body Weight')");

                            t.HasCheckConstraint("CK_CustomExercises_LoadModel", "\"LoadModel\" IN ('external','full_bodyweight','bodyweight_context_only','reps_only')");

                            t.HasCheckConstraint("CK_CustomExercises_LoadStep", "\"LoadStepKg\" >= 0 AND \"LoadStepKg\" <= 50");

                            t.HasCheckConstraint("CK_CustomExercises_LoadStepUnit", "\"LoadStepUnit\" IN ('kg','lb')");

                            t.HasCheckConstraint("CK_CustomExercises_TrackingMode", "\"TrackingMode\" IN ('reps','duration')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.EquipmentLoadDefault", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableLoadsJson")
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double?>("LoadStepKg")
                        .HasColumnType("double precision");

                    b.Property<string>("LoadStepUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("kg");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Equipment")
                        .IsUnique();

                    b.ToTable("EquipmentLoadDefaults", null, t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentLoadDefaults_LoadStepUnit", "\"LoadStepUnit\" IN ('kg','lb')");

                            t.HasCheckConstraint("CK_EquipmentLoadDefaults_OneRule", "\"LoadStepKg\" IS NULL OR \"AvailableLoadsJson\" IS NULL");

                            t.HasCheckConstraint("CK_EquipmentLoadDefaults_Step", "\"LoadStepKg\" IS NULL OR (\"LoadStepKg\" >= 0 AND \"LoadStepKg\" <= 50)");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Free Weights");

                    b.Property<string>("Cue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoadModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<double>("LoadStepKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5);

                    b.Property<string>("MovementPattern")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SecondaryMusclesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("reps");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exercises_Category", "\"Category\" IN ('Free Weights','Machine','Body Weight')");

                            t.HasCheckConstraint("CK_Exercises_LoadModel", "\"LoadModel\" IN ('external','full_bodyweight','bodyweight_context_only','reps_only')");

                            t.HasCheckConstraint("CK_Exercises_LoadStep", "\"LoadStepKg\" >= 0 AND \"LoadStepKg\" <= 50");

                            t.HasCheckConstraint("CK_Exercises_TrackingMode", "\"TrackingMode\" IN ('reps','duration')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Normalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("Normalized")
                        .IsUnique();

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseHistoryClear", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedWorkouts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("RemovedSets")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ExerciseId", "ClearedAt");

                    b.ToTable("ExerciseHistoryClears");
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseLoadSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableLoadsJson")
                        .HasColumnType("text");

                    b.Property<double?>("LoadStepKg")
                        .HasColumnType("double precision");

                    b.Property<string>("LoadStepUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("kg");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.ToTable("ExerciseLoadSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExerciseLoadSettings_LoadStepUnit", "\"LoadStepUnit\" IN ('kg','lb')");

                            t.HasCheckConstraint("CK_ExerciseLoadSettings_OneRule", "\"LoadStepKg\" IS NULL OR \"AvailableLoadsJson\" IS NULL");

                            t.HasCheckConstraint("CK_ExerciseLoadSettings_Step", "\"LoadStepKg\" IS NULL OR (\"LoadStepKg\" >= 0 AND \"LoadStepKg\" <= 50)");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<double>("LastE1rmKg")
                        .HasColumnType("double precision");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("Stalls")
                        .HasColumnType("integer");

                    b.Property<double>("TrendE1rmKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ExerciseId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Progress_ExercisePerUser");

                    b.ToTable("Progress", null, t =>
                        {
                            t.HasCheckConstraint("CK_Progress_E1rm", "\"TrendE1rmKg\" >= 0 AND \"LastE1rmKg\" >= 0");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseSubstitution", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OriginalExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PendingRetention")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReplacementExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplacementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RetainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourcePhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceSlotKey")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceTemplateExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "SessionId", "PendingRetention");

                    b.ToTable("ExerciseSubstitutions");
                });

            modelBuilder.Entity("Workout.Api.Data.GoogleHealthConnection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ConnectionGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("EncryptedGoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedStepHistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleIdHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrantedScopesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("WorkoutLastSuccessfulSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WorkoutSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("WorkoutSyncRevision")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("GoogleIdHash")
                        .IsUnique();

                    b.ToTable("GoogleHealthConnections");
                });

            modelBuilder.Entity("Workout.Api.Data.GoogleHealthOAuthState", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedOperationsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedScopesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("State");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("GoogleHealthOAuthStates");
                });

            modelBuilder.Entity("Workout.Api.Data.GoogleHealthWorkoutSyncWork", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ConnectionGeneration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DesiredDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DesiredFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesiredName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DesiredNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DesiredRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DesiredStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleIdHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleOperationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleResourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastErrorCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessfulSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("ProcessingState", "NextAttemptAt");

                    b.HasIndex("UserId", "WorkoutSessionId")
                        .IsUnique();

                    b.ToTable("GoogleHealthWorkoutSyncWork");
                });

            modelBuilder.Entity("Workout.Api.Data.IntegrationGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("CentralConnectionGeneration")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CentralConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Peer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "Peer")
                        .IsUnique();

                    b.ToTable("IntegrationGrants");
                });

            modelBuilder.Entity("Workout.Api.Data.MutationReceipt", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Created");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("Workout.Api.Data.NutritionContextCache", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SummaryFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("SummaryFrom")
                        .HasColumnType("date");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("text");

                    b.Property<string>("SummaryTimeZone")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SummaryTo")
                        .HasColumnType("date");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NutritionContexts");
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramDayProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PassedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "RunId", "Week", "Attempt");

                    b.HasIndex("UserId", "RunId", "Week", "Attempt", "TemplateId")
                        .IsUnique();

                    b.ToTable("ProgramDayProgresses");
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramPhase", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePageFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePageTo")
                        .HasColumnType("integer");

                    b.Property<int>("WeekFrom")
                        .HasColumnType("integer");

                    b.Property<int>("WeekTo")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "Position")
                        .IsUnique();

                    b.HasIndex("UserId", "ProgramId", "WeekFrom", "WeekTo");

                    b.ToTable("ProgramPhases");
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramRun", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentAttempt")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "CompletedAt");

                    b.HasIndex("UserId", "ProgramId", "Number")
                        .IsUnique();

                    b.ToTable("ProgramRuns");
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramSkip", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("SkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "ProgramId", "TemplateId")
                        .IsUnique();

                    b.ToTable("ProgramSkips");
                });

            modelBuilder.Entity("Workout.Api.Data.ResourceGeneration", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("CustomExercises")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseLoads")
                        .HasColumnType("bigint");

                    b.Property<long>("History")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("HistoryAppendId")
                        .HasColumnType("uuid");

                    b.Property<long>("Imports")
                        .HasColumnType("bigint");

                    b.Property<long>("Preferences")
                        .HasColumnType("bigint");

                    b.Property<long>("Programs")
                        .HasColumnType("bigint");

                    b.Property<long>("Progress")
                        .HasColumnType("bigint");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint");

                    b.Property<long>("Templates")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("ResourceGenerations");
                });

            modelBuilder.Entity("Workout.Api.Data.SessionExercise", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BaselineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DemoLinksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean");

                    b.Property<string>("LoadModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("external");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("PrescriptionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgressionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SequenceGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourcePhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceSlotKey")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceTemplateExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubstitutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SwapGroupKey")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "SessionId", "Position");

                    b.HasIndex("UserId", "SessionId", "SourceSlotKey");

                    b.ToTable("SessionExercises");
                });

            modelBuilder.Entity("Workout.Api.Data.TemplateExercise", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DemoLinksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("SequenceGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SlotKey")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<string>("SubstitutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "TemplateId", "Position");

                    b.HasIndex("UserId", "TemplateId", "SlotKey")
                        .IsUnique();

                    b.ToTable("TemplateExercises");
                });

            modelBuilder.Entity("Workout.Api.Data.TrainingProgram", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("standby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceImportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weeks")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Programs_ActivePerUser")
                        .HasFilter("\"Active\"");

                    b.ToTable("Programs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Programs_Lifecycle", "\"LifecycleStatus\" IN ('standby','active','completed')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.TrainingReadModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Kind", "SourceId");

                    b.ToTable("TrainingReadModels");
                });

            modelBuilder.Entity("Workout.Api.Data.WatchDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAt", "ExpiresAt");

                    b.ToTable("WatchDevices");
                });

            modelBuilder.Entity("Workout.Api.Data.WatchPairing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DeviceTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedStatusAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PairingCodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PairingCodeHash");

                    b.ToTable("WatchPairings");
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutPushDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("WorkoutPushDevices");
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutRestAlertSchedule", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Generation")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("UserId", "SessionId", "DeviceId", "Generation")
                        .IsUnique();

                    b.ToTable("WorkoutRestAlertSchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutRestAlertSchedules_Status", "\"Status\" IN ('pending','scheduled','dispatching','accepted','cancelled','disabled','expired','failed')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutSession", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BodyWeightSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTimingEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NutritionContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("NutritionContextRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PausedSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid?>("ProgramDayProgressId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RestDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RestDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RestGeneration")
                        .HasColumnType("text");

                    b.Property<string>("RestOriginDeviceId")
                        .HasColumnType("text");

                    b.Property<long?>("RestPausedRemainingMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RestStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("idle");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("StartPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Workouts_ActivePerUser")
                        .HasFilter("\"Active\"");

                    b.HasIndex("UserId", "FinishedAt");

                    b.HasIndex("UserId", "ProgramDayProgressId");

                    b.ToTable("Workouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Workouts_RestStatus", "\"RestStatus\" IN ('idle','running','paused','elapsed')");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ActiveCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BaselineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhaseWeek")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProgramPhaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Templates_ActivePerUser")
                        .HasFilter("\"Active\"");

                    b.HasIndex("UserId", "ProgramId", "ProgramPhaseId");

                    b.HasIndex("UserId", "ProgramId", "Week", "Position");

                    b.ToTable("Templates", null, t =>
                        {
                            t.HasCheckConstraint("CK_Templates_ActiveStandalone", "NOT \"Active\" OR \"ProgramId\" IS NULL");
                        });
                });

            modelBuilder.Entity("Workout.Api.Data.AiConversation", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.AiConversationTurn", b =>
                {
                    b.HasOne("Workout.Api.Data.AiConversation", "Conversation")
                        .WithMany("Turns")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Workout.Api.Data.AiImport", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.AiUsage", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.AuthSession", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.CompletedSet", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.CustomExercise", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.EquipmentLoadDefault", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseAlias", b =>
                {
                    b.HasOne("Workout.Api.Data.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseHistoryClear", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseLoadSetting", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseProgress", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ExerciseSubstitution", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.GoogleHealthConnection", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.GoogleHealthOAuthState", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.GoogleHealthWorkoutSyncWork", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.IntegrationGrant", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.MutationReceipt", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.NutritionContextCache", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramDayProgress", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramPhase", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramRun", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ProgramSkip", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.ResourceGeneration", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.SessionExercise", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.TemplateExercise", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.TrainingProgram", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.TrainingReadModel", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WatchDevice", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutPushDevice", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutRestAlertSchedule", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workout.Api.Data.WorkoutSession", null)
                        .WithMany()
                        .HasForeignKey("UserId", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutSession", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.WorkoutTemplate", b =>
                {
                    b.HasOne("Workout.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workout.Api.Data.AiConversation", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
