import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { ErrorBoundary } from './components/ui/ErrorBoundary';
import '@fontsource-variable/inter/index.css';
import {applyTheme, initialTheme} from './lib/theme';
import {trackInputModality} from './lib/inputModality';
import './index.css';
import './layout.css';
import './motion.css';
import './workout.css';
applyTheme(initialTheme());
trackInputModality();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ErrorBoundary><App /></ErrorBoundary></React.StrictMode>);
